### ISSUE TITLE
Página oficial em https://denuntiare.github.io

### ISSUE THREAD

**Issue by manoelcampos** [Denuntiare/Landing-Page#1]
Não sei se sabe, mas se renomear o repositório Landing-Page para denuntiare.github.io,
a página do projeto poderá ser acessada diretamente de https://denuntiare.github.io

E parabéns pelo projeto, muito bacana mesmo 😄

**Comment by LucasMGcode** [comment]
Obrigado Professor Emanoel!
Eu não sabia dessa informação e fico agradecido pela atenção. Porém eu não me ative a esse problema antes pois planejava comprar o domínio http://denuntiare.com.br/, acho que a intenção em deixar o endereço mais limpo é mesma.

Novamente muitíssimo obrigado pela atenção e pelo elogio :smiley:
